-- Ejecutar en Supabase SQL Editor.
-- La secret key no debe colocarse en archivos publicos ni en codigo del navegador.

begin;

create table if not exists public.payment_installments (
  id bigint generated by default as identity primary key,
  month_number integer not null unique check (month_number between 1 and 12),
  period_label text not null,
  due_amount numeric(12, 2) not null default 451.72 check (due_amount >= 0),
  due_date date,
  paid_amount numeric(12, 2) not null default 0 check (paid_amount >= 0),
  paid_at date,
  receipt_path text,
  receipt_url text,
  notes text,
  updated_at timestamptz not null default now()
);

alter table public.payment_installments enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.payment_installments to anon, authenticated;
grant insert, update, delete on public.payment_installments to authenticated;
grant usage, select on sequence public.payment_installments_id_seq to authenticated;

drop policy if exists payment_installments_read_all on public.payment_installments;
create policy payment_installments_read_all
on public.payment_installments
for select
to anon, authenticated
using (true);

drop policy if exists payment_installments_admin_insert on public.payment_installments;
create policy payment_installments_admin_insert
on public.payment_installments
for insert
to authenticated
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
);

drop policy if exists payment_installments_admin_update on public.payment_installments;
create policy payment_installments_admin_update
on public.payment_installments
for update
to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
)
with check (
  lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
);

drop policy if exists payment_installments_admin_delete on public.payment_installments;
create policy payment_installments_admin_delete
on public.payment_installments
for delete
to authenticated
using (
  lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
);

insert into public.payment_installments (month_number, period_label, due_amount, due_date)
select
  n,
  'Mes ' || n,
  451.72,
  (date '2026-07-02' + ((n - 1) * interval '1 month'))::date
from generate_series(1, 12) as n
on conflict (month_number) do update
set
  period_label = excluded.period_label,
  due_amount = excluded.due_amount,
  due_date = excluded.due_date;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'payment-receipts',
  'payment-receipts',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists payment_receipts_public_read on storage.objects;
create policy payment_receipts_public_read
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'payment-receipts');

drop policy if exists payment_receipts_admin_insert on storage.objects;
create policy payment_receipts_admin_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'payment-receipts'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
);

drop policy if exists payment_receipts_admin_update on storage.objects;
create policy payment_receipts_admin_update
on storage.objects
for update
to authenticated
using (
  bucket_id = 'payment-receipts'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
)
with check (
  bucket_id = 'payment-receipts'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
);

drop policy if exists payment_receipts_admin_delete on storage.objects;
create policy payment_receipts_admin_delete
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'payment-receipts'
  and lower(coalesce(auth.jwt() ->> 'email', '')) = 'andrezarate1234@gmail.com'
);

commit;
